Product.create!(title: 'Livingroom'   , price: 800  , category: :room)
Product.create!(title: 'Kitchen'      , price: 600  , category: :room)
Product.create!(title: 'Bedrooms'     , price: 600  , category: :room)
Product.create!(title: 'Bathrooms'    , price: 600  , category: :room)
Product.create!(title: 'Custom Time'  , price: 400  , category: :room)
Product.create!(title: 'Windows'      , price: 200  , category: :option)
Product.create!(title: 'Ironing'      , price: 50   , category: :option)
Product.create!(title: 'Oven'         , price: 300  , category: :option)
Product.create!(title: 'Fridge'       , price: 400  , category: :option)
Product.create!(title: 'Cabinets'     , price: 400  , category: :option)
Product.create!(title: 'Chemicals'    , price: 1000 , category: :material)
Product.create!(title: 'Utensils'     , price: 1000 , category: :material)

Discount.create!(coupon: 'EVERYWEEK'    , discount_type: :percentage  , value: 10   , recurring: true)
Discount.create!(coupon: 'EVERY2WEEKS'  , discount_type: :percentage  , value: 5    , recurring: true)
Discount.create!(coupon: '100OFF'       , discount_type: :fixed       , value: 100  , recurring: false)
Discount.create!(coupon: 'FIRSTCLEAN10' , discount_type: :percentage  , value: 10   , recurring: false)

User.create!(email: 'admin@getshiny.ru' , password: 'password'  , password_confirmation: 'password')
